spring.application.name=FridgeCheff
rapidapi.key=e25037fdadmsh7061cda4b31836dp1e00edjsnd747e103e0e4
server.address=0.0.0.0
server.port=8080
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.codec.max-in-memory-size=100MB
